name: 'Composite action for jamstack'
inputs:
  app-location: 
    default: '/'
    required: true
runs:
  using: "composite"
  steps:
      # To use this repository's private action,
      # you must check out the repository
#       - name: Checkout
#         uses: actions/checkout@v3  
#       - name: Install Azure-cli
#         uses: elstudio/action-install-azure-cli@v1
#       - name: Log in to Azure Container Registry
#         uses: docker/login-action@v2.0.0
#         with: 
#          registry: jamstacktest.azurecr.io
#          username: ${{ inputs.username }}
#          password: ${{ inputs.password }} 
       # This is a separate action that sets up buildx runner
      # - name: Cache NPM dependencies
      #   uses: actions/cache@v3
      #   with:
      #    path: |
      #       npm
      #     # node_modules
      #    key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
      #    restore-keys: |
      #     ${{ runner.OS }}-npm-cache-    
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
         path: |
           .npm
          **/node_modules
         key: ${{ runner.OS }}-npm2-cache-${{ hashFiles('**/package-lock.json') }}
         restore-keys: |
          ${{ runner.OS }}-npm2-cache-
#       - name: Cache node modules
#         id: cache-npm
#         uses: actions/cache@v3
#         env:
#           cache-name: cache-node-modules
#         with:
#           # npm cache files are stored in `~/.npm` on Linux/macOS
#           path: ~/.npm
#           key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.os }}-build-${{ env.cache-name }}-
#             ${{ runner.os }}-build-
#             ${{ runner.os }}-   
#       - name: Cache Node Modules
#         id: node-cache
#         uses: actions/cache@v2
#         with:
#           path: node_modules
#           key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Oryx build step
        uses: snehapar9/jamstack-docker-action@snehapar/oryx-build
        id: oryx-build
        with:
          app-location: ${{ inputs.app-location }}
